FROM maven:3.9-eclipse-temurin-26

WORKDIR /workspace

COPY pom.xml ./pom.xml
RUN mvn -B -ntp -DskipTests dependency:go-offline

COPY src ./src

EXPOSE 8080
CMD ["mvn", "-B", "-ntp", "spring-boot:run", "-Dspring-boot.run.fork=false"]
