import type { PublicAdmissionsCalendar } from './admissionsContracts'

export const OFFICIAL_ADMISSIONS_CALENDAR_2027_I: PublicAdmissionsCalendar = {
  title: 'Pregrado presencial 2027-I',
  callName: 'Primer semestre académico de 2027',
  updatedAt: '15 de septiembre de 2026',
  checkedAt: '6 de octubre de 2026',
  source: {
    label: 'Calendario de admisiones publicado por la UPTC',
    url: 'https://reportes.uptc.edu.co/sitio/portal/sitios/universidad/vic_aca/adm_reg/1aspi/pre/',
  },
  registrationSource: {
    label: 'Inscripción de pregrado presencial publicada por la UPTC',
    url: 'https://www.uptc.edu.co/sitio/portal/sitios/universidad/vic_aca/adm_reg/1aspi/pre/pap_preg.html',
  },
  confirmationSource: {
    label: 'Comunicado institucional sobre la convocatoria 2027-I',
    url: 'https://dsp.uptc.edu.co/sitio/portal/cal_not_eve/noticias/det/UPTC-abre-inscripciones-para-estudiar-un-pregrado-presencial-a-distancia-o-virtual-el-proximo-semestre/',
  },
  officialActSource: {
    label: 'Resolución 111 de 2026',
    url: 'https://apps3.uptc.edu.co/compilacion-normativa-web/#/compilaciones-normativas/detalle-documento/9906',
  },
  sourceNote: 'El considerando menciona 2026-II; el título y el artículo 1 fijan 2027-I. Esta agenda toma las fechas del artículo 1. Para el pago de matrícula, consulta el calendario académico 2027-I citado allí: el plazo de derechos pecuniarios no es una fecha de matrícula.',
  milestones: [
    {
      id: 'promotion-window',
      startsOn: '2026-09-21',
      endsOn: '2026-10-23',
      dateLabel: '21 sep – 23 oct 2026',
      title: 'Promoción en página web y emisoras',
      description: 'La Resolución 111 de 2026 fija este periodo de promoción para la convocatoria de pregrado presencial.',
      kind: 'application',
    },
    {
      id: 'pin-sale',
      startsOn: '2026-09-21',
      endsOn: '2026-10-21',
      dateLabel: '21 sep – 21 oct 2026',
      title: 'Venta de pines de inscripción',
      description: 'La publicación de admisiones de UPTC registra este intervalo para los programas presenciales. Consulta la fuente oficial para conocer los medios, valores y condiciones vigentes.',
      kind: 'application',
    },
    {
      id: 'online-registration',
      startsOn: '2026-09-21',
      endsOn: '2026-10-23',
      dateLabel: '21 sep – 23 oct 2026',
      title: 'Registro de inscripción por internet',
      description: 'Ventana de inscripción publicada para programas de pregrado presencial. Continúa el trámite en los canales oficiales de UPTC.',
      kind: 'application',
    },
    {
      id: 'application-close',
      startsOn: '2026-10-23',
      endsOn: '2026-10-23',
      dateLabel: 'Hasta el 23 oct 2026',
      title: 'Cierre de inscripciones',
      description: 'La fecha de cierre publicada para registrar la inscripción de pregrado presencial.',
      kind: 'application',
    },
    {
      id: 'disability-medical-exam',
      startsOn: '2026-10-27',
      endsOn: '2026-10-27',
      dateLabel: '27 oct 2026',
      title: 'Valoración médica para aspirantes con discapacidad',
      description: 'Fecha indicada en el artículo 1 de la Resolución 111. Consulta con UPTC las indicaciones oficiales y los ajustes disponibles.',
      kind: 'selection',
    },
    {
      id: 'sign-language-test',
      startsOn: '2026-10-27',
      endsOn: '2026-10-27',
      dateLabel: '27 oct 2026',
      title: 'Prueba de lengua de señas para aspirantes sordos',
      description: 'Fecha del acto para esta prueba. La agenda solo informa el calendario y no solicita información de salud ni de discapacidad.',
      kind: 'selection',
    },
    {
      id: 'special-tests',
      startsOn: '2026-10-28',
      endsOn: '2026-10-29',
      dateLabel: '28 y 29 oct 2026',
      title: 'Pruebas especiales',
      description: 'La publicación de admisiones de UPTC incluye pruebas para Artes Plásticas y Visuales, Licenciatura en Educación Física, Recreación y Deporte, y Licenciatura en Música. La prueba de aptitud se realiza en la sede del programa.',
      kind: 'selection',
    },
    {
      id: 'special-medical-physical-exams',
      startsOn: '2026-10-28',
      endsOn: '2026-10-29',
      dateLabel: '28 y 29 oct 2026',
      title: 'Exámenes médicos y físicos asociados',
      description: 'La Resolución señala estas fechas para los exámenes asociados a las pruebas de aptitud; consulta la información oficial del programa.',
      kind: 'selection',
    },
    {
      id: 'icfes-information-verification',
      startsOn: '2026-10-28',
      endsOn: '2026-10-29',
      dateLabel: '28 y 29 oct 2026',
      title: 'Verificación de información ICFES',
      description: 'El artículo 1 ubica la verificación de información ICFES en estas fechas. Esta pantalla no recoge ni valida datos personales.',
      kind: 'selection',
    },
    {
      id: 'registration-correction-deadline',
      startsOn: '2026-11-10',
      endsOn: '2026-11-10',
      dateLabel: 'Hasta el 10 nov 2026',
      title: 'Corrección o anulación de información errónea',
      description: 'Fecha límite publicada para corregir o anular información errónea en la inscripción. Verifica el canal oficial de atención.',
      kind: 'application',
    },
    {
      id: 'sira-admissions-process',
      startsOn: '2026-11-11',
      endsOn: '2026-11-12',
      dateLabel: '11–12 nov 2026',
      title: 'Proceso de admisión en SIRA',
      description: 'El calendario ubica aquí el proceso de admisión en SIRA. Esta agenda no reproduce ni automatiza criterios de selección.',
      kind: 'selection',
    },
    {
      id: 'results',
      startsOn: '2026-11-13',
      endsOn: '2026-11-13',
      dateLabel: '13 nov 2026',
      title: 'Publicación de resultados',
      description: 'Fecha publicada para los resultados de pregrado presencial.',
      kind: 'selection',
    },
    {
      id: 'ise-form',
      startsOn: '2026-11-17',
      endsOn: '2026-11-27',
      dateLabel: '17–27 nov 2026',
      title: 'Formulario de registro ISE',
      description: 'Ventana publicada para el formulario de registro ISE, posterior a la publicación de resultados.',
      kind: 'enrollment',
    },
    {
      id: 'ise-correction-window',
      startsOn: '2026-11-18',
      endsOn: '2026-12-04',
      dateLabel: '18 nov – 4 dic 2026',
      title: 'Corrección o subsanación de ISE y documentos',
      description: 'Periodo publicado para corregir o subsanar la información del ISE y los documentos según las indicaciones oficiales.',
      kind: 'enrollment',
    },
    {
      id: 'pecuniary-rights-payment',
      startsOn: '2026-11-23',
      endsOn: '2026-12-10',
      dateLabel: '23 nov – 10 dic 2026',
      title: 'Pago de derechos pecuniarios',
      description: 'Intervalo fijado en la Resolución 111 para el pago de derechos pecuniarios de la convocatoria presencial.',
      kind: 'enrollment',
    },
    {
      id: 'course-registration-admitted',
      startsOn: '2026-12-09',
      endsOn: '2026-12-14',
      dateLabel: '9–14 dic 2026',
      title: 'Registro de asignaturas por las Escuelas',
      description: 'La resolución asigna este registro de asignaturas a las Escuelas para los aspirantes admitidos.',
      kind: 'enrollment',
    },
    {
      id: 'waitlist-call',
      startsOn: '2026-12-09',
      endsOn: '2026-12-15',
      dateLabel: '9–15 dic 2026',
      title: 'Llamado a opcionados',
      description: 'Periodo de llamados publicado para aspirantes opcionados de pregrado presencial y FESAD.',
      kind: 'enrollment',
    },
    {
      id: 'waitlist-ise-documents',
      startsOn: '2026-12-09',
      endsOn: '2026-12-15',
      dateLabel: '9–15 dic 2026',
      title: 'ISE y entrega de documentos para opcionados',
      description: 'Periodo previsto en el calendario para quienes reciban el llamado de opcionados.',
      kind: 'enrollment',
    },
    {
      id: 'waitlist-ise-correction',
      startsOn: '2026-12-10',
      endsOn: '2026-12-16',
      dateLabel: '10–16 dic 2026',
      title: 'Corrección de ISE y documentos para opcionados',
      description: 'Periodo publicado para correcciones y subsanaciones de opcionados.',
      kind: 'enrollment',
    },
    {
      id: 'waitlist-pecuniary-rights-payment',
      startsOn: '2026-12-10',
      endsOn: '2026-12-17',
      dateLabel: '10–17 dic 2026',
      title: 'Pago de derechos pecuniarios para opcionados',
      description: 'Intervalo indicado en el artículo 1 para los derechos pecuniarios de opcionados.',
      kind: 'enrollment',
    },
    {
      id: 'waitlist-course-registration',
      startsOn: '2026-12-10',
      endsOn: '2026-12-18',
      dateLabel: '10–18 dic 2026',
      title: 'Registro de asignaturas para opcionados',
      description: 'Periodo publicado para el registro de asignaturas de quienes sean llamados como opcionados.',
      kind: 'enrollment',
    },
    {
      id: 'second-option-quota-assignment',
      startsOn: '2026-12-14',
      endsOn: '2026-12-14',
      dateLabel: '14 dic 2026',
      title: 'Asignación de cupo especial de segunda opción',
      description: 'La fecha remite a la Resolución 5362 de 2025; esta vista no define criterios ni asigna cupos.',
      kind: 'selection',
    },
  ],
}
