import type { PublicAdmissionsCalendar } from './admissionsContracts'

export const OFFICIAL_ADMISSIONS_CALENDAR_2027_I: PublicAdmissionsCalendar = {
  title: 'Pregrado presencial 2027-I',
  callName: 'Primer semestre académico de 2027',
  updatedAt: '15 de septiembre de 2026',
  checkedAt: '4 de octubre de 2026',
  source: {
    label: 'Calendario de admisiones publicado por la UPTC',
    url: 'https://reportes.uptc.edu.co/sitio/portal/sitios/universidad/vic_aca/adm_reg/1aspi/pre/',
  },
  confirmationSource: {
    label: 'Comunicado institucional sobre la convocatoria 2027-I',
    url: 'https://dsp.uptc.edu.co/sitio/portal/cal_not_eve/noticias/det/UPTC-abre-inscripciones-para-estudiar-un-pregrado-presencial-a-distancia-o-virtual-el-proximo-semestre/',
  },
  officialActSource: {
    label: 'Resolución 111 de 2026',
    url: 'https://apps3.uptc.edu.co/compilacion-normativa-web/#/compilaciones-normativas/detalle-documento/9906',
  },
  milestones: [
    {
      id: 'pin-sale',
      startsOn: '2026-09-21',
      endsOn: '2026-10-21',
      dateLabel: '21 sep – 21 oct 2026',
      title: 'Venta de pines de inscripción',
      description: 'La publicación de admisiones de UPTC registra este intervalo para los programas presenciales. Consulta la fuente oficial para conocer los medios, valores y condiciones vigentes.',
      kind: 'application',
    },
    {
      id: 'application-close',
      startsOn: '2026-10-23',
      endsOn: '2026-10-23',
      dateLabel: 'Hasta el 23 oct 2026',
      title: 'Cierre de inscripciones',
      description: 'La fecha de cierre publicada para registrar la inscripción de pregrado presencial.',
      kind: 'application',
    },
    {
      id: 'special-tests',
      startsOn: '2026-10-28',
      endsOn: '2026-10-29',
      dateLabel: '28 y 29 oct 2026',
      title: 'Pruebas especiales',
      description: 'La publicación de admisiones de UPTC incluye pruebas para Artes Plásticas y Visuales, Licenciatura en Educación Física, Recreación y Deporte, y Licenciatura en Música.',
      kind: 'selection',
    },
    {
      id: 'results',
      startsOn: '2026-11-13',
      endsOn: '2026-11-13',
      dateLabel: '13 nov 2026',
      title: 'Publicación de resultados',
      description: 'Fecha publicada para los resultados de pregrado presencial.',
      kind: 'selection',
    },
    {
      id: 'ise-form',
      startsOn: '2026-11-17',
      endsOn: '2026-11-27',
      dateLabel: '17–27 nov 2026',
      title: 'Formulario de registro ISE',
      description: 'Ventana publicada para el formulario de registro ISE, posterior a la publicación de resultados.',
      kind: 'enrollment',
    },
    {
      id: 'tuition-and-enrollment',
      startsOn: '2026-11-23',
      endsOn: '2026-12-10',
      dateLabel: '23 nov – 10 dic 2026',
      title: 'Derechos pecuniarios y matrícula',
      description: 'Intervalo publicado para el pago de derechos pecuniarios y la matrícula de pregrado presencial.',
      kind: 'enrollment',
    },
    {
      id: 'waitlist-call',
      startsOn: '2026-12-09',
      endsOn: '2026-12-15',
      dateLabel: '9–15 dic 2026',
      title: 'Llamado a opcionados',
      description: 'Periodo de llamados publicado para aspirantes opcionados de pregrado presencial y FESAD.',
      kind: 'enrollment',
    },
  ],
}
